In [1]:
#np is an alias, In Python alias are an alternate name for referring to the same thing.
import numpy as np 

In [7]:
#creating a numpy array
arr = np.array([1,2,3])
print(arr)
print(type(arr)) #numpy array object ndarray

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
#to check numpy version
print(np.__version__)

1.24.2


In [8]:
#using tuple to create a numpy array
arr = np.array((1,2,3))
print(arr)

[1 2 3]


In [9]:
# 0-Dimension array
arr = np.array(10)
print(arr)

10


In [10]:
# 1-Dimension array
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [13]:
# 2-Dimension array (1-D arrays as its elements)
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [15]:
# 3-Dimension array (2-D arrays as its elements)
arr = np.array([[[1,2,3],[4,5,6]],[[7,2,8],[4,7,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[7 2 8]
  [4 7 9]]]


In [16]:
#checking the number of dimensions of array 
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [17]:
#defining number of dimensions using (ndmin) argument
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


#Array Indexing

In [18]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [19]:
print(arr[2])

3


In [20]:
print(arr[0] + arr[2])

4


In [21]:
#accessing 2-D arrays
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1]) #first argument for rows and second argument for columns

2nd element on 1st row:  2


In [22]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4]) #first argument for rows and second argument for columns

5th element on 2nd row:  10


In [23]:
#accessing 3-D arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[1, 1, 1])

11


In [24]:
#Negative Indexing
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


#slicing

In [26]:
#Slice elements from index 1 to index 5 from the following array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5]) #result includes the start index but excludes the end index

[2 3 4 5]


In [27]:
#Slice elements from the beginning to index 4 (not included)
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [28]:
#Negative slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [29]:
#using step value
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [30]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [31]:
#2-D array slicing
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [32]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [33]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


#Data Types

In [1]:
import numpy as np 
#Integer
arr = np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [2]:
#String
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [3]:
#creating array with the defined data type
arr = np.array([1,2,3,4], dtype="S")
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [4]:
arr = np.array([1, 2, 3, 4], dtype='i4') #it will create an array with integer data type having 4 bytes size
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [5]:
#Converting data type on existing array 
arr = np.array([1.1, 2.1, 3.1])
print(arr)
print(arr.dtype)
newarr = arr.astype("i")
print(newarr)
print(newarr.dtype)

[1.1 2.1 3.1]
float64
[1 2 3]
int32


#Copy and View 

In [10]:
arr = np.array([1,2,3,4,5]) #making any change will not effect the other array
arr1 = arr.copy()
arr[1]=8
print(arr)
print(arr1)
print(arr1.base)

[1 8 3 4 5]
[1 2 3 4 5]
None


In [11]:
arr = np.array([1,2,3,4,5]) #making any change will effect the other array
arr1 = arr.view()
arr[1]=8
print(arr)
print(arr1)
print(arr1.base)

[1 8 3 4 5]
[1 8 3 4 5]
[1 8 3 4 5]


#Array Shape

In [12]:
#Getting shape of the 2-D array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [13]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


#Reshape

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
